In [ ]:
## Text Classifier for Category detection

In [2]:
import pandas as pd
from sklearn.utils import shuffle
import os
cwd = os.getcwd()
print(cwd)
os.chdir('C:\\Users\\G560667\\Category Classification')
print(cwd)

C:\Users\G560667\Category Classification
C:\Users\G560667\Category Classification


In [3]:
df = pd.read_excel('Data Set-Train test.xlsx')

In [4]:
df.CATEGORY
dt_train_test=df[['CATEGORY','QUICK']]
dt_train_test=shuffle(dt_train_test)
dt_train_test.head()

CATEGORY                    QUICK
105      Home     Exterminators prices
172      Home   Refelt pool table cost
19   Wellness              Yoga prices
142      Home   Lawn mower repair cost
285    Events  Wedding planning prices

In [5]:
import pandas as pd
from sklearn.cross_validation  import train_test_split
from matplotlib import pyplot as plt

training_data=dt_train_test['QUICK']
test_data=dt_train_test['CATEGORY']

X_train, X_test, y_train, y_test = train_test_split(training_data, test_data, test_size=0.2)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

X_train.head()
y_train.head()

(255,) (255,)
(64,) (64,)


165        Home
270      Events
89         Home
94         Home
14     Wellness
Name: CATEGORY, dtype: object

In [6]:
##Extract features
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
counts = count_vectorizer.fit_transform(X_train.values)

In [ ]:
examples = ['Math tutor prices']
example_counts = count_vectorizer.transform(examples)
predictions = counts.predict(example_counts)
predictions

In [8]:
##Pipelining-Test Data Split
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report
from nltk.classify.scikitlearn import SklearnClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

pipeline = Pipeline([
    ('vectorizer',  CountVectorizer()),
    ('classifier',  MultinomialNB()) ])

pipeline.fit(X_train.values, y_train.values)
pipeline.predict(examples)
predictions=pipeline.predict(X_test)
cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
#score = f1_score(y_test, predictions,pos_label=average)
#scores.append(score)
#plt.imshow(cm, cmap='binary')
#plt.show()

#y_test.head()

[[ 0  2  5  0  0  0]
 [ 0 11  2  0  0  0]
 [ 0  0 35  0  0  0]
 [ 0  1  3  1  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  2  0  0  0]]
F1 score:  0.324268759929

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         7
     Events       0.69      0.85      0.76        13
       Home       0.74      1.00      0.85        35
    Lessons       1.00      0.20      0.33         5
       Pets       0.00      0.00      0.00         2
   Wellness       0.00      0.00      0.00         2

avg / total       0.63      0.73      0.65        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
##N gram approach-Test Data Split

from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix as cm
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report

pipeline_ngram = Pipeline([
    ('count_vectorizer', CountVectorizer(ngram_range=(1, 2))),
    ('classifier',       MultinomialNB())
])
pipeline_ngram.fit(X_train.values, y_train.values)
pipeline_ngram.predict(examples)
predictions=pipeline_ngram.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))

[[ 1  2  4  0  0  0]
 [ 0 11  2  0  0  0]
 [ 0  0 35  0  0  0]
 [ 0  0  2  3  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  1  0  0  1]]
F1 score:  0.672370682919

 clasification report:
              precision    recall  f1-score   support

   Business       1.00      0.14      0.25         7
     Events       0.79      0.85      0.81        13
       Home       0.80      1.00      0.89        35
    Lessons       1.00      0.60      0.75         5
       Pets       1.00      0.50      0.67         2
   Wellness       1.00      0.50      0.67         2

avg / total       0.84      0.81      0.78        64



In [10]:
##Ngram and TFIDF--Test Data Split

from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix as cm
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report

pipeline_tfidf = Pipeline([
    ('count_vectorizer',   CountVectorizer(stop_words='english')),
    ('tfidf_transformer',  TfidfTransformer()),
    ('classifier',         MultinomialNB())
])

pipeline_tfidf.fit(X_train.values, y_train.values)
pipeline_tfidf.predict(examples)
predictions=pipeline_tfidf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))

[[ 0  2  5  0  0  0]
 [ 0 11  2  0  0  0]
 [ 0  0 35  0  0  0]
 [ 0  0  4  1  0  0]
 [ 0  0  2  0  0  0]
 [ 0  0  2  0  0  0]]
F1 score:  0.333836098542

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         7
     Events       0.85      0.85      0.85        13
       Home       0.70      1.00      0.82        35
    Lessons       1.00      0.20      0.33         5
       Pets       0.00      0.00      0.00         2
   Wellness       0.00      0.00      0.00         2

avg / total       0.63      0.73      0.65        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [11]:
from  sklearn.grid_search import GridSearchCV
parameters = {'count_vectorizer__ngram_range': [(1, 1), (1, 2)],
               'tfidf_transformer__use_idf': (True, False),
              'classifier__alpha': (1e-2, 1e-3),
 }

gs_clf = GridSearchCV(pipeline_tfidf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_

[[ 3  2  2  0  0  0]
 [ 0 11  2  0  0  0]
 [ 0  2 32  0  0  1]
 [ 0  0  1  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  2]]
F1 score:  0.827248677249

 clasification report:
              precision    recall  f1-score   support

   Business       1.00      0.43      0.60         7
     Events       0.73      0.85      0.79        13
       Home       0.86      0.91      0.89        35
    Lessons       1.00      0.80      0.89         5
       Pets       1.00      1.00      1.00         2
   Wellness       0.67      1.00      0.80         2

avg / total       0.86      0.84      0.84        64



{'classifier__alpha': 0.001,
 'count_vectorizer__ngram_range': (1, 2),
 'tfidf_transformer__use_idf': False}

In [12]:
## Bernouili NB--Test data Split
from sklearn.naive_bayes import BernoulliNB

pipeline_NB = Pipeline([
    ('count_vectorizer',   CountVectorizer(stop_words='english')),
    ('classifier',         BernoulliNB()) ])

pipeline_NB.fit(X_train.values, y_train.values)
pipeline_NB.predict(examples)
pipeline_NB.predict(X_test)

array(['Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Events', 'Home', 'Home', 'Home', 'Home', 'Home', 'Events', 'Home',
       'Home', 'Events', 'Events', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Home', 'Home', 'Events', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Events', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Home', 'Home', 'Events', 'Events', 'Home', 'Home', 'Home',
       'Home', 'Home', 'Events', 'Home', 'Home', 'Home', 'Home', 'Events',
       'Home', 'Home', 'Home', 'Events', 'Home', 'Home', 'Home', 'Home'], 
      dtype='<U8')

In [13]:
from  sklearn.grid_search import GridSearchCV
parameters = {'count_vectorizer__ngram_range': [(1, 1), (1, 2)],
               'classifier__binarize': (1e-2, 1e-3,0.1,0.0),
 }

gs_clf = GridSearchCV(pipeline_NB, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_

[[ 0  1  6  0  0  0]
 [ 0  7  6  0  0  0]
 [ 0  0 35  0  0  0]
 [ 0  1  4  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  2  0  0  0]]
F1 score:  0.229797979798

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         7
     Events       0.64      0.54      0.58        13
       Home       0.66      1.00      0.80        35
    Lessons       0.00      0.00      0.00         5
       Pets       0.00      0.00      0.00         2
   Wellness       0.00      0.00      0.00         2

avg / total       0.49      0.66      0.55        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


{'classifier__binarize': 0.01, 'count_vectorizer__ngram_range': (1, 1)}

In [20]:
## Stemming and Multinomial Naive BAYES

from  sklearn.grid_search import GridSearchCV
import nltk
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = SnowballStemmer("english", ignore_stopwords=True)

class StemmedCountVectorizer(CountVectorizer):
    def __init__(self, stemmer):
        super(StemmedCountVectorizer, self).__init__()
        self.stemmer = stemmer
        
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

stemmed_count_vect = StemmedCountVectorizer(stemmer)

text_mnb_stemmed = Pipeline([('vect', stemmed_count_vect),
                      ('tfidf', TfidfTransformer()),
                      ('mnb', MultinomialNB(fit_prior=False)),
 ])

parameters = {'tfidf__use_idf': (True, False),
              'mnb__alpha': (1e-2, 1e-3),
 }

gs_clf = GridSearchCV(text_mnb_stemmed, parameters,)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_

[[ 4  2  1  0  0  0]
 [ 1 10  2  0  0  0]
 [ 2  1 30  1  0  1]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  2]]
Accuracy:  0.828125
F1 score:  0.822017198488

 clasification report:
              precision    recall  f1-score   support

   Business       0.57      0.57      0.57         7
     Events       0.77      0.77      0.77        13
       Home       0.91      0.86      0.88        35
    Lessons       0.83      1.00      0.91         5
       Pets       1.00      1.00      1.00         2
   Wellness       0.67      1.00      0.80         2

avg / total       0.83      0.83      0.83        64



{'mnb__alpha': 0.01, 'tfidf__use_idf': True}

In [40]:
examples = ['i want a massage']
predictions = gs_clf.predict_proba(examples)
predicted_Class = gs_clf.predict(examples)
print(predictions)
print(predicted_Class)

[[  2.15077121e-03   9.35213540e-04   4.63019359e-04   1.93902175e-03
    5.01948349e-03   9.89492491e-01]]
['Wellness']


In [36]:
probabllties_definition_index=['Business','Events','Home','Lessons','Pets','Wellness']