In [13]:
## Text Classifier for Category detection

In [95]:
import pandas as pd
from sklearn.utils import shuffle
import os
cwd = os.getcwd()
print(cwd)
os.chdir('C:\\Users\\G560667\\Category Classification')
print(cwd)

C:\Users\G560667\Category Classification
C:\Users\G560667\Category Classification


In [19]:
df = pandas.read_excel('Data Set-Train test.xlsx')
df.category

In [96]:
df.CATEGORY
dt_train_test=df[['CATEGORY','QUICK']]
dt_train_test=shuffle(dt_train_test)
dt_train_test.head()

CATEGORY                     QUICK
122     Home       Grout cleaning cost
99      Home  Dryer vent cleaning cost
105     Home      Exterminators prices
67      Home     Appliance repair cost
177     Home          Roof repair cost

In [76]:
##Extract features
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
counts = count_vectorizer.fit_transform(df ['QUICK'].values)

In [97]:
import pandas as pd
from sklearn.cross_validation  import train_test_split
from matplotlib import pyplot as plt

training_data=dt_train_test['QUICK']
test_data=dt_train_test['CATEGORY']

X_train, X_test, y_train, y_test = train_test_split(training_data, test_data, test_size=0.2)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

X_train.head()
y_train.head()

(255,) (255,)
(64,) (64,)


304    Business
113        Home
100        Home
25         Pets
30      Lessons
Name: CATEGORY, dtype: object

In [72]:
##Extract features
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
counts = count_vectorizer.fit_transform(X_train.values)

In [77]:
examples = ['Math tutor prices']
example_counts = count_vectorizer.transform(examples)
predictions = classifier.predict(example_counts)
predictions

array(['Lessons'], 
      dtype='<U8')

In [144]:
##Pipelining-Test Data Split
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix as cm
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report

pipeline = Pipeline([
    ('vectorizer',  CountVectorizer()),
    ('classifier',  MultinomialNB()) ])

pipeline.fit(X_train.values, y_train.values)
pipeline.predict(examples)
predictions=pipeline.predict(X_test)
cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
#score = f1_score(y_test, predictions,pos_label=average)
#scores.append(score)
#plt.imshow(cm, cmap='binary')
#plt.show()

#y_test.head()

[[ 0  2  2  0  0  0]
 [ 0 14  3  0  0  0]
 [ 0  0 27  0  0  0]
 [ 0  3  4  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  3  2  0  0  0]]
F1 score:  0.501709401709

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         4
     Events       0.64      0.82      0.72        17
       Home       0.71      1.00      0.83        27
    Lessons       1.00      0.30      0.46        10
       Pets       1.00      1.00      1.00         1
   Wellness       0.00      0.00      0.00         5

avg / total       0.64      0.70      0.63        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [147]:
##N gram approach-Test Data Split

from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix as cm
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report

pipeline_ngram = Pipeline([
    ('count_vectorizer', CountVectorizer(ngram_range=(1, 2))),
    ('classifier',       MultinomialNB())
])
pipeline_ngram.fit(X_train.values, y_train.values)
pipeline_ngram.predict(examples)
predictions=pipeline_ngram.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))

[[ 1  2  1  0  0  0]
 [ 0 14  3  0  0  0]
 [ 0  0 27  0  0  0]
 [ 0  3  2  5  0  0]
 [ 0  0  0  0  1  0]
 [ 0  3  2  0  0  0]]
F1 score:  0.609263854425

 clasification report:
              precision    recall  f1-score   support

   Business       1.00      0.25      0.40         4
     Events       0.64      0.82      0.72        17
       Home       0.77      1.00      0.87        27
    Lessons       1.00      0.50      0.67        10
       Pets       1.00      1.00      1.00         1
   Wellness       0.00      0.00      0.00         5

avg / total       0.73      0.75      0.70        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [148]:
##Ngram and TFIDF--Test Data Split

from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix as cm
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score,accuracy_score,classification_report

pipeline_tfidf = Pipeline([
    ('count_vectorizer',   CountVectorizer(stop_words='english')),
    ('tfidf_transformer',  TfidfTransformer()),
    ('classifier',         MultinomialNB())
])

pipeline_tfidf.fit(X_train.values, y_train.values)
pipeline_tfidf.predict(examples)
predictions=pipeline_tfidf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))

[[ 0  0  4  0  0  0]
 [ 0  8  9  0  0  0]
 [ 0  0 27  0  0  0]
 [ 0  0  8  2  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  5  0  0  0]]
F1 score:  0.273333333333

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         4
     Events       1.00      0.47      0.64        17
       Home       0.50      1.00      0.67        27
    Lessons       1.00      0.20      0.33        10
       Pets       0.00      0.00      0.00         1
   Wellness       0.00      0.00      0.00         5

avg / total       0.63      0.58      0.50        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [154]:
from  sklearn.grid_search import GridSearchCV
parameters = {'count_vectorizer__ngram_range': [(1, 1), (1, 2)],
               'tfidf_transformer__use_idf': (True, False),
              'classifier__alpha': (1e-2, 1e-3),
 }

gs_clf = GridSearchCV(pipeline_tfidf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_

[[ 2  1  1  0  0  0]
 [ 0 14  3  0  0  0]
 [ 1  0 25  1  0  0]
 [ 0  2  0  6  1  1]
 [ 0  0  0  0  1  0]
 [ 0  0  1  0  0  4]]
F1 score:  0.740783330876

 clasification report:
              precision    recall  f1-score   support

   Business       0.67      0.50      0.57         4
     Events       0.82      0.82      0.82        17
       Home       0.83      0.93      0.88        27
    Lessons       0.86      0.60      0.71        10
       Pets       0.50      1.00      0.67         1
   Wellness       0.80      0.80      0.80         5

avg / total       0.82      0.81      0.81        64



{'classifier__alpha': 0.01,
 'count_vectorizer__ngram_range': (1, 1),
 'tfidf_transformer__use_idf': False}

In [103]:
## Bernouili NB--Test data Split
from sklearn.naive_bayes import BernoulliNB

pipeline_NB = Pipeline([
    ('count_vectorizer',   CountVectorizer(stop_words='english')),
    ('classifier',         BernoulliNB()) ])

pipeline_NB.fit(X_train.values, y_train.values)
pipeline_NB.predict(examples)
pipeline_NB.predict(X_test)
X_test

182                   Sink installation cost
134             Ikea furniture assembly cost
187                      Stump grinding cost
219                           Bartender cost
220               Boudoir photography prices
161                         Pipe repair cost
204              Washing machine repair cost
3                        Health coach prices
158                  Personal organizer cost
70                       Asphalt repair cost
181                       Shower repair cost
0                          Career coach cost
9                             Massage prices
240                          Florists prices
10                    Medical massage prices
120     Garage doors prices and installation
169                 Property management fees
216      Average cost of wedding invitations
150                    Microwave repair cost
26      How much does it cost to board a cat
300                  Freelance editing rates
38                                ESL prices
12        

In [156]:
from  sklearn.grid_search import GridSearchCV
parameters = {'count_vectorizer__ngram_range': [(1, 1), (1, 2)],
               'classifier__binarize': (1e-2, 1e-3,0.1,0.0),
 }

gs_clf = GridSearchCV(pipeline_NB, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_

[[ 0  0  4  0  0  0]
 [ 0  8  9  0  0  0]
 [ 0  0 27  0  0  0]
 [ 0  0 10  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  5  0  0  0]]
F1 score:  0.215100401606

 clasification report:
              precision    recall  f1-score   support

   Business       0.00      0.00      0.00         4
     Events       1.00      0.47      0.64        17
       Home       0.48      1.00      0.65        27
    Lessons       0.00      0.00      0.00        10
       Pets       0.00      0.00      0.00         1
   Wellness       0.00      0.00      0.00         5

avg / total       0.47      0.55      0.44        64



C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\G560667\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


{'classifier__binarize': 0.01, 'count_vectorizer__ngram_range': (1, 1)}

In [ ]:
from  sklearn.grid_search import GridSearchCV
import nltk
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english", ignore_stopwords=True)
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')
text_mnb_stemmed = Pipeline([('count_vectorizer', stemmed_count_vect),
                      ('tfidf', TfidfTransformer()),
                      ('mnb', MultinomialNB(fit_prior=False)),
 ])

parameters = {'count_vectorizer__ngram_range': [(1, 1), (1, 2)],
               'tfidf__use_idf': (True, False),
              'mnb__alpha': (1e-2, 1e-3),
 }

gs_clf = GridSearchCV(pipeline_tfidf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train.values, y_train.values)
gs_clf.predict(examples)
predictions=gs_clf.predict(X_test)

cm = confusion_matrix (y_test, predictions)
print(cm)
#print ('Accuracy: ',accuracy_score(y_test, predictions))
print ('F1 score: ',f1_score(y_test, predictions,average='macro'))
print ('\n clasification report:\n', classification_report(y_test,predictions))
gs_clf.best_score_
gs_clf.best_params_